### ISSUE TITLE
Choose my own resource name for shared resources

### ISSUE THREAD

**Issue by sebster** [passbolt/passbolt_api#102]
When a password resource is shared with me by another user, I would to use my own resource name for it instead of the name provided by the owner. This allows me to follow my own naming conventions and keep my list clean and ranked the way I want it to be.

**Comment by technogenus** [comment]
The same password resource - with different names... by user?  So what would be the common key/reference for everyone?  This should be a 'team' database, so you really should have 'team' naming conventions and policies.

**Comment by sebster** [comment]
Well perhaps I'm abusing the resource name at the moment as there is no tagging/grouping feature yet. I'm naming my passwords "utilities-telecom-sprint" for example, with a reverse hierarchical notation (most generic category first), so that when sorting by resource name passwords are neatly grouped, and so I can quickly filter for a category (for example dev team passwords start with department1-dev- and operations passwords with department2-ops). If I'm part of multiple teams they might have different naming conventions or non-compatible naming conventions. I can also make the name more clear for myself.

**Comment by stripthis** [comment]
Hopefully the upcoming categories and tagging functionalities will help you with your use case @sebster. I'm marking this as an enhancement but it is unlikely to happen unless more people voice their support, as this is currently not possible without an important change in the data model.

**Comment by bluenetinc** [comment]
I agree with technogenus that you should not need an additional personalized name (teams SHOULD have standards for naming conventions), however I COULD see value in having a second field "alias" that would be useful after categories/tags comes out.  I too use reverse hierarchical notation, which I think would be valuable to continue using even when tags/categories is available (particularly to ensure uniqueness when EXPORTING passwords).  But an alias field (which we could choose to display instead of the name perhaps) that could be shorter, and easier to find/read (since the column width is a bit narrow for my longer hierarchical notation names), and would be very convenient if/when the credentials are already in a folder or tree-view.

**Comment by sebster** [comment]
An extra personal display name field would be perfect for me. It means that the original resource name is preserved in case I need to find the resource by the actual name, and I can still choose to display it by a name of my own choosing.

Also note that this feature is just a "nice to have" for me, and I just wanted to share the idea.

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-a-logged-in-user-i-can-choose-my-own-resource-name-alias-for-resources-shared-with-me/60
