### ISSUE TITLE
Fields validation rules are too strict

### ISSUE THREAD

**Issue by sebster** [passbolt/passbolt_api#103]
When I try to use certain characters in my resource names, I get a validation message that only certain characters are supported. The list is currently incorrect (it says that it supports colon but it does not), but other than that I am wondering why these restrictions are there at all.

From a user perspective, it's simply a name used to list the passwords, and why can't I use spaces and punctuation at will?

**Comment by technogenus** [comment]
This has been mentioned in numerous threads.  You should take some time to read through similar requests and then post additional information there.

**Comment by sebster** [comment]
Hi,

Thanks for the reply. Sorry if I'm reporting in the wrong place!

Before posting I checked all open issues and read the "guidelines for contributing" document, but I did not find this specific issue (I saw a similar one about user names).

I'm not sure which threads/forum you are referring to, perhaps the desired procedure can be added to the "Reporting regular issues" section of the "guidelines for contributing", or the README.

**Comment by kevinmuller** [comment]
Hi @sebster 

Thanks for reporting. This is indeed an issue that has been reported several times in different places. We are planning to restructure our support channels soon so that the information is better organized.
 
These strict validation rules on fields are there for historical reasons. We have a task in our backlog regarding this (ref: PASSBOLT-1293). The strategy would be to remove these validation rules from the API (and to accept any kind of content basically), and replace them by a simple content filtering at the client side (to avoid XSS, ...). This task is important but is going to be tedious, and we are still in discussions internally to understand what would be the overall impact on the security aspects. 

Anyone having a feedback about the strategy we are planning to implement is more than welcome.

**Comment by kevinmuller** [comment]
@sebster regarding the supporter characters list currently being incorrect, it will be fixed in the next release. There is a task in our current sprint to address this (and make the validation a bit more flexible). (ref: PASSBOLT-1934 and PASSBOLT-1256)

**Comment by technogenus** [comment]
Recommend looking at two basic text functions...  cleanse for inbound DB text field data and render for outbound then ensure all record entry panels employ the cleanse and all output to html employ the render.  Could either handle on page, or even extend the base db functions to bolt there.  Start with simple eliminates for special characters, then gradually extended these two functons with more complex 'replace' (ASCII codes) and multi-language consideration.  Since it would be only two base functions, improvements or changes would affect all db writes and render outputs and the render would return the correct to text to the edit box, which is then re-parsed by the cleanse.

**Comment by ktosiek** [comment]
You shouldn't even need explicit escaping with Passbolt's architecture, so just letting the whole Unicode into comments/usernames should work fine ;-)

**Comment by stripthis** [comment]
Moved to https://community.passbolt.com/t/as-a-logged-in-user-i-can-use-any-utf8-character-for-resource-name-descriptions-comments-etc/58
