### ISSUE TITLE
As a user who have not completed the setup clicking on the passbolt browser icon, I should not connect directly to the demo site

### ISSUE THREAD

**Issue by bluenetinc** [passbolt/passbolt_api#111]
When the user has a roaming firefox/google chrome profile, they sit down to a new computer (not registered with our passbolt server), see the "passbolt extension" icon, click on it, and don't understand why when they attempt to recover their account it says they are an invalid user.

End-users simply don't realize that they are connecting to demo.passbolt.com, and it is not the same as our site.

Because there isn't a good document for branding/customizing the passbolt login site yet (or maybe I just couldn't find it. - Which files can I edit to add some branding/logos?  Is there a document on how/where to modify this?).  Would it be possible to not make the demo.passbolt.com/auth/login site look EXACTLY like the production/installed site, and have a obvious graphic and/or watermark that says: THIS IS A DEMO PAGE?

**Comment by stripthis** [comment]
Hi @bluenetinc 

Thank you for your suggestions. We are aware of this issue and our plan is to implement a new start page when people click on the passbolt browser icon when the plugin is not configured. We should design a specific landing page to explain the status as well as options (use the demo, connect to an instance that is already install, create one in passbolt cloud when the offer will be present, etc.). Ref.     PASSBOLT-1353

Concerning the customization capability there is no documentation indeed or "easy" way to change the logo at the moment. However you can modifiy the CSS by adding a file to app/webroot/css and link to it in app/View/Elements/css.tp. Otherwise you can also fork the passbolt styleguide and regenerate the main css to your liking: https://github.com/passbolt/passbolt_styleguide . If you have further questions on look and feel customization please open a separate issue as to keep discussions focused on a single issue.

Cheers,

**Comment by bryanmathers** [comment]
Moved to: https://community.passbolt.com/t/as-a-user-who-has-not-completed-the-setup-clicking-on-the-passbolt-browser-icon-i-should-not-connect-directly-to-the-demo-site/52
(plus more stories)
