### ISSUE TITLE
As an admin, while deleting a user who is the sole owner of a password that is shared, I should be able to transfer the ownership to another user in order to be able to perform the deletion.

### ISSUE THREAD

**Issue by kumaip** [passbolt/passbolt_api#133]
Hi I am admin but when I try to delete a user, i get this message:

You are trying to delete the user "xxxx"!

This user is the sole owner of 1 password: xxxxxxx. You need to transfer the ownership to other users before you can proceed.

I thought this bug was fixed in the version 1.6.0 ?

And I've already upgraded to the last version:

Application

Current version:
  #1497890584 1497890584_Migration_1.6.0
Latest version:
  #1497890584 1497890584_Migration_1.6.0
---------------------------------------------------------------
Migrations Plugin

Current version:
  #003 003_increase_class_name_length
Latest version:
  #003 003_increase_class_name_length

Thanks in advance for yours response

**Comment by kevinmuller** [comment]
Hi @kumaip 

Thanks for the report. It is a known limitation which will be fixed very soon.

This system is there to make sure that the integrity of the data is not compromised when deleting a user. Since a password needs a owner, before deleting a user that is the sole owner of one or several shared passwords, it is necessary that the ownership of these passwords are transferred to another user. Otherwise, the possibility to manage these passwords will be lost.

We are aware that currently this scenario has some limitations (such as making it difficult for an admin to delete some users), and have a task planned for this sprint to improve this: PASSBOLT-2289:As an admin, while deleting a user who is the sole owner of a password that is shared, I should be able to transfer the ownership to another user in order to be able to perform the deletion.

We'll keep you updated on this thread once it is implemented.

**Comment by bryanmathers** [comment]
Moved to: https://community.passbolt.com/t/as-an-admin-while-deleting-a-user-who-is-the-sole-owner-of-a-password-that-is-shared-i-should-be-able-to-transfer-the-ownership-to-another-user-in-order-to-be-able-to-perform-the-deletion/45
(plus other stories)
