### ISSUE TITLE
Does this firefox plugin security issue also apply to passbolt for firefox?

### ISSUE THREAD

**Issue by mannp** [passbolt/passbolt_api#138]
> https://www.mailvelope.com/en/blog/security-warning-mailvelope-in-firefox

**Comment by stripthis** [comment]
Yes, this apply to all firefox addon (not just passbolt or mailvelope). We collaborate closesly with Thomas from Mailevelope on a number of issues, and we share the same conclusions on the impact level. This should be fixed in November 2017 when Firefox SDK extensions are discountinued. In the meantime firefox users should be extra carefull which addons they run along side passbolt or mailvelope.

see. https://twitter.com/passbolt/status/860140272851722241

**Comment by mannp** [comment]
Ok thanks, so is it mentioned on your site or the instructions as a warning, as I wouldn't think to go looking for one message on twitter from whenever it was?

I'll stick to chrome then.

**Comment by stripthis** [comment]
It's not on our website at the moment because we believe that the risk is too broad. E.g. we consider this type of threat (e.g. when a user install a malicious application that have access to the file system) to be out of passbolt security model.

We will mention this however in an upcoming "security" page, that explains the risks we have considered and the mitigations that are in place (or still need to be implemented), as well as the one we see as out of scope. Thank you for your patience.
