### ISSUE TITLE
As an administrator I can add users that have not completed the setup to a group

### ISSUE THREAD

**Issue by pblajev** [passbolt/passbolt_api#144]
I think it will be great if there is a way to share passwords with everyone.

To better explain what I mean here is my current workaround:
1- Create a group
2- Add everybody to the group
3- Share passwords with the group
4- Create new users
5- Wait for users to register and create/upload their keys
6- Add new users to the group

If step 6 is automated that will be awesome.

Maybe an extra option in group's preferences that a "post-user_registration" process will check for and if it's enabled then it will automatically add the newly registered  user to the group.

Thank you,

-- Peter

**Comment by stripthis** [comment]
Hi @pblajev, the core team have seen this request before and while it makes sense it is not trivial to implement due to the security model. E.g. one need the user to provide public key before sharing a password, and this is done during the setup. However we had in mind in the future to allow to perform share/encryption in an async' fashion to allow the scenario you describe. Do not hold your breath, as it won't come this year.

**Comment by pblajev** [comment]
Hi @stripthis, I suggested automated actions AFTER the user has completed registration.

Anyway, thanks for the great product.

**Comment by stripthis** [comment]
@pblajev yes, we are talking about the same thing. I meant to say that the process your describe is not easy to implement but it the right way to go. Cheers,

**Comment by bryanmathers** [comment]
Moved to: 
https://community.passbolt.com/t/as-an-administrator-i-can-add-users-that-have-not-completed-the-setup-to-a-group/42
(plus other stories)
