### ISSUE TITLE
Validation rules are too strict. For example "+" is not allowed in the email field, or "\", "#" and "\n" are not allowed in the comment or URL field

### ISSUE THREAD

**Issue by LegendPJ** [passbolt/passbolt_api#17]
Hi,

When I create a new password on the web interface, I could not use the "+" in the login or the comment.
There's a  similar issue : #14 

Thanks

**Comment by kevinmuller** [comment]
Hi @LegendPJ ,

Thanks for the feedback. Indeed this issue is very similar to #14.

The good news is that #14 is already part of our current sprint. So I'll just update the issue and make sure we fix login and comment on the same time. Just in case, we'll also check if this concerns other fields.

The reference to the internal issue is: PASSBOLT-1637 . The same should appear in the next release notes to come.

Cheers.

**Comment by LegendPJ** [comment]
Great ! 

thank's for your response !

**Comment by p4tpr0** [comment]
Hi,

Login and comment should allow any character (accented letters, etc.). I just tried to create a new password with "clé" as username, and got bounced. Few minutes earlier I was refused this comment "username = client id".

thanks!

**Comment by silvaireboivert** [comment]
Hello,

I'd add the character '\'  , in my case it's to reference a UNC path in the description field . 
'\n' in the Description also triggers the "description should only contain .." error

Thanks,

**Comment by kevinmuller** [comment]
Thanks for your feedback @silvaireboivert. 

The refactoring of the validation rules to make them more permissive is planned in our current sprint. It will fix the issue that you are mentioning, and allow a much larger set of characters. It will be available in the next release (which will come faster than the last one, promise!) I will keep you updated on this thread once it is implemented and stable.

Cheers,

**Comment by stripthis** [comment]
See. #40
