### ISSUE TITLE
As a logged in user I should be able to change my private/public key

### ISSUE THREAD

**Issue by Ducatel** [passbolt/passbolt_api#170]
Hi Passbolt team,

There is a way to rotate GPG key ?
If no, there is a plan for that ?

Thanks

**Comment by stripthis** [comment]
Hello David, there is indeed a plan to allow rotating public/private keys. ref. PASSBOLT-2395 but probably not this year. In the meantime you could create another user and transfer your passwords to them and then switch to that user.

In order to change the private key passphrase you can export your private key, change the passphrase in another gpg compatible tool (gnupg command line tool for example), then do a recover and import the udpated key.

Thanks for your patience.

**Comment by Ducatel** [comment]
OK, thanks ;)

So, this feature should be linked with the expiration date of key.
And also it should be possible to rotate the server key.

Ps: just small question, what do you mean by  "As a LU" in the issue title ?

**Comment by stripthis** [comment]
> Ps: just small question, what do you mean by "As a LU" in the issue title ?

LU = logged in user, it's a convention we use a bit everywhere in the tests. We try to avoid abbreviations in tickets, but I typed this one too quickly this time.

Other abbreviation also includes:
AN = anonymou user without plugin
AP = anonymous user with plugin
GM = group manager
AD = administrator
etc.

**Comment by Ducatel** [comment]
Ok, I understand now.
Maybe you should but this list inside the contributing.md ?

**Comment by bryanmathers** [comment]
Moved to: https://community.passbolt.com/t/as-a-logged-in-user-i-should-be-able-to-change-my-private-public-key/36
(other stories are there too)
