### ISSUE TITLE
Pressing Enter instead of hitting OK button will not remember passphrase for 5 minutes

### ISSUE THREAD

**Issue by mattgillan** [passbolt/passbolt_api#173]
This can be reproduced as follows:
- Click on a password to bring up the master passphrase prompt
- Check the 'Remember it for 5 minutes' box
- Type your master passphrase and press enter
- The passphrase prompt disappears but the 5 minute remember feature does not get applied

Clicking the OK button while going through this process works as intended.

**Comment by passboltUser** [comment]
I and some other user can confirm this.

**Comment by bcraft73** [comment]
We also rolled it out, but I'm curious about an estimated delivery on this bug fix...

**Comment by passboltUser** [comment]
Interesting that the devs still didn't reply anything about this patch?

**Comment by Jameskr97** [comment]
Ehh, there haven't been regular commits since this issue was created. I'd call this project somewhat inactive atm.

**Comment by kevinmuller** [comment]
The project is very much active and all our energy is on the release of the V2.0.0 at the moment.

We are also planning to fix this as part of the V2.0.0, as well as to improve the remember me feature so that it can remember the master passphrase for more than 5 minutes. (See design proposal below).
![71804a689bb0b1fdcb2e8b139b24f790c1403b85](https://user-images.githubusercontent.com/80405/35631329-9ad5ad1e-06c9-11e8-8988-0aabcfed2109.png)

You can also see the post about it in the community forum: https://community.passbolt.com/t/as-logged-in-user-i-should-be-able-to-get-passbolt-to-remember-my-private-key-password-for-more-than-5-minutes/43, where you can give feedback about how you'd like this to be improved.

Bear with us, it's coming soon!

**Comment by Jameskr97** [comment]
Is everything discussed on the community forum instead of here?

**Comment by kevinmuller** [comment]
Bugs are discussed here. So, for this discussion github is the right place. For anything else (feature requests, installation issues, ...), it's on the forum.

**Comment by passboltUser** [comment]
Thanks for clarifying, I was hoping you'd fix this in the upcoming v2.0.

**Comment by stripthis** [comment]
Fixed with v2.0
