### ISSUE TITLE
Unable to login to new user forum

### ISSUE THREAD

**Issue by mannp** [passbolt/passbolt_api#194]
I have created an account and its sends me the confirm email, but when I try and confirm I get the following error

> ["BAD CSRF"]

Also, why are alot of items being moved to the forum for discussion, when those items are not really for discussion but rather to be implemented or not...

Will the forum be upgraded to https too :)

**Comment by stripthis** [comment]
@mannp maybe have a look there: https://meta.discourse.org/search?q=BAD%20CSRF

> Also, why are alot of items being moved to the forum for discussion, when those items are not really for discussion but rather to be implemented or not...

We also want to move the discussions happening via direct email to the team (there is a lot of it and you can't see it) to this place and only keep the bugs on github to reduce the team workload. We're trying to setup a new place for feature request and change request in the form of forum so that community in a larger sense (e.g. not just github users) can upvote and add comments. 

This is a work in progress to bear with us as we make that move. We want to try it as we believe it will benefit the community as a whole.

**Comment by mannp** [comment]
Perfectly normal and a great idea, just odd some of the ones being moved :)

Wow, so I cannot confirm my account in Firefox, but can in Chrome....didn't have that problem with other discourse forums ...?

Leave it with you and it will be good to get some 'buzz' in the forums for your product.

**Comment by stripthis** [comment]
Thanks for the bug report, we've reported the issue to discourse, it seems that the http:// urls are not redirecting properly to https.
