### ISSUE TITLE
An admin of a passbolt install should be able to restrict access to peoples/groups from an LDAP directory

### ISSUE THREAD

**Issue by p4tpr0** [passbolt/passbolt_api#22]
Hello,

I've been very happy to find "LDAP integration" on the roadmap, but when I think about it I can find different use cases that need different developments.
As a Sysadmin (and CISO) in a university one of my main challenges is to provide my users with exclusive and secured access to resources. 
- Authentication on passbolt looks very robust, falling back to LDAP login/password is not an option.
- Having a script every night that pulls new users from LDAP to inject them in passbolt could do the trick, but it'll probably create 70 to 80% never-used accounts. It can be done out of passbolt scope, though.
- An interesting option would be to allow self-registration to people only if they can authenticate first against an LDAP directory. The registration process would also pull user details (Name, email, pict?...) from the LDAP.
- A nice add-on would be to sync groups from LDAP (crontab for example), and to make it possible for a user to share a secret with a group.

**Comment by nodens** [comment]
Hi !
Actually I think LDAP auth could be an addition to the current auth model.
That is, you'd need both LDAP access and your key. The key would be generated on first login.

The idea is that in larger organisations, you expect to be able to revoke access by simply de-activating the LDAP account of an employee for instance.

Of course it means 2 secrets are needed to authenticate but for having used and been involved in the design of an in-house developped web password management app, the users deal well with it, since they understand that the "second password" they need is what actually protect the data. Also an agent can be used for the key secret if available.

**Comment by Kage** [comment]
Hello!

What's the status of this?  Where is contribution needed?

**Comment by stripthis** [comment]
@Kage there is no change in status since 2016. I think a first good step would be to write the functional specifications (user stories and user acceptance test scenarios).

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/an-admin-of-a-passbolt-install-should-be-able-to-restrict-access-to-peoples-groups-from-an-ldap-directory/76
