### ISSUE TITLE
Issue with sending emails 

### ISSUE THREAD

**Issue by atefehzaker** [passbolt/passbolt_api#220]
## Problem with sending emails
Hello there,
I apologize if the answer to this is obvious. I’m new at this.
I am using passbolt's unofficial docker(dlen/passbolt-compose) on my server.(the one at https://github.com/dlen/passbolt-compose)

### What I did
No emails are being sent out by my Passbolt server.I verified that there are several emails in the queue using the command  su -s /bin/bash -c " /var/www/passbolt/app/Console/cake EmailQueue.sender" nginx in my container. the settings for my dockerized passbolt.env file is like this:
...
 EMAIL_TRANSPORT=Smtp
 EMAIL_FROM=info@mywebsite.com
 EMAIL_HOST=smtp.mywebsite.com
 EMAIL_PORT=25
 EMAIL_TIMEOUT=300
 EMAIL_USERNAME=info@mywebsite.com
 EMAIL_PASSWORD=mywebsites-password
 EMAIL_TLS=true

### What happened
when I run the command: su -s /bin/bash -c " /var/www/passbolt/app/Console/cake EmailQueue.sender" nginx in my container, nothing shows up. I also checked the logs to find errors. but there is nothing there as well. I changed the port to 587, rebuild the docker-compose and again nothing happens. the status for my crated user is "Activation pending". not email comes to users to be activated. and when I run  su -s /bin/bash -c "/var/www/passbolt/app/Console/cake EmailQueue.preview" nginx I can see mails that are to be sent to the users. can anyone help me with this please?

**Comment by ghaberek** [comment]
The problem is that there is a limit on the number of attempts passbolt will make when attempting to send your messages. If you've exhausted the limit then it will silently ignore the queued message during an `EmailQueue.sender` call but still show it during an `EmailQueue.preview` call. Notice how `send_tries` is set to `4` in the table below.

    MariaDB [passbolt]> SELECT id,subject,sent,send_tries FROM email_queue;
    
    +--------------------------------------+----------------------------+------+------------+
    | id                                   | subject                    | sent | send_tries |
    +--------------------------------------+----------------------------+------+------------+
    | 5a5644b9-5560-4ab6-a16f-4cce0a0a0064 | Welcome to passbolt, Greg! |    0 |          4 |
    +--------------------------------------+----------------------------+------+------------+

You can reset the `send_tries` value and it should send with the next call to `EmailQueue.sender`.

    MariaDB [passbolt]> UPDATE email_queue SET send_tries = 0 WHERE id = '5a5644b9-5560-4ab6-a16f-4cce0a0a0064';

It's a frustrating problem because your email configuration is probably correct now but you can't tell. I have requested a change to this behavior in this community thread: https://community.passbolt.com/t/as-an-admin-i-should-be-able-to-see-when-queued-emails-will-not-be-sent/279

Also, I'd recommend seeking further help on the community site and not the Github issues page, as recommended in the [README](https://github.com/passbolt/passbolt_api/blob/master/README.md):

> ## Contributing to passbolt
> 
> Please check out CONTRIBUTING.md for more information on how to get involved!
> 
> **Please only use github to report bug or make a pull request.**
> 
> If you want to make a feature request or if you are having an issue when installing your own passbolt instance you should seek help first from the community here: https://community.passbolt.com/

**Comment by atefehzaker** [comment]
thank you so much @ghaberek
