### ISSUE TITLE
Deleted users cannot be recreated 

### ISSUE THREAD

**Issue by OdyX** [passbolt/passbolt_api#224]
* Passbolt Version: 701a4bb3bc0f6dbc813dba1cf534675df92ab459 (2.0.0-rc1+)
* Platform and Target:
-- Operating system: Debian Stretch 9.3
-- PHP: 7.0.27-0+deb9u1
-- Web server: Apache 2.4.25-3+deb9u3
-- Database server: MariaDB 10.1.26-0+deb9u1

### What you did
After an activation link has expired, I didn't find a way to resend an activation link; so I deleted the user, in the hope that it would allow me to re-set it up, but the API tells me the username is already taken (true, it still exists in the DB, with deleted=1)

### What you expected to happen
From an administrator point of view, I expect the delete-then-create process to work, or a way for me to re-send an activation link…

**Comment by kevinmuller** [comment]
Hi @OdyX ,

Thanks for the bug report. We could reproduce it, and it's a regression from V1.x. It will be fixed in the V2.0.0-rc2 which will be released in a few days.

When a token expires, starting an account recovery procedure (/recover) will send another activation link to the user. We are planning to improve this workflow to make it more intuitive though.

**Comment by stripthis** [comment]
Fixed with rc2
