### ISSUE TITLE
.ch is not valid in the email validator

### ISSUE THREAD

**Issue by Salzi** [passbolt/passbolt_api#243]
## .ch is not valid for the mail validator
* Passbolt Version: 2.0.1
* Platform and Target:
-- Operating system: Debian 9
-- PHP: 7.0
-- Web server: apache2
-- Database server: mysql

### What you did
Fresh install on a stock debian 9. Followed the instructions at https://help.passbolt.com/hosting/install/ce/debian-9-stretch.html
During the Installation when asked to create a new user I entered:

```
User email aka username
> j.salzmann@COMPANYNAME.ch
First name
> J
Last name
> Salzmann
```

### What happened
Got the error

```
Validation failed for the following user data:
- Username: The username should be a valid email address.
User registration failed.
```

### What you expected to happen
When I replaced the `.ch` in the mail by `.com` it works as expected. But .ch should be a valid tld.

**Comment by kevinmuller** [comment]
Hi @Salzi ,

.ch is supposed to validate. You are probably getting this error because the domain name can't be reached from inside your host. The validation rule makes sure that the domain exists.

You can see the validation rule that is used here: https://github.com/cakephp/cakephp/blob/master/src/Validation/Validation.php#L738

**Comment by Salzi** [comment]
Hi @kevinmuller 
Thank you very much for your very quick answer and you're totally right: It was a DNS error
