### ISSUE TITLE
SSL detection not working in healthcheck

### ISSUE THREAD

**Issue by kevinmuller** [passbolt/passbolt_api#27]
Issue reported by [patpro](https://twitter.com/p4tpr0/status/788793980007964673) on twitter:

SSL is not detected properly in healthcheck, even though the healthcheck page is accessed through HTTPS. (cf screenshot below).

<img width="811" alt="screen shot 2016-10-19 at 22 09 12" src="https://cloud.githubusercontent.com/assets/80405/19535631/cb8decfc-9648-11e6-8b3a-f5579c6efc0b.png">

Ticket reference: PASSBOLT-1721

**Comment by p4tpr0** [comment]
Just in case you have not dug into this, it's quite easy to fix.
Just change file app/Controller/HealthCheckController.php to use this line:

$this->_checks['ssl'] = ($this->request->is('ssl') && configure::read('App.ssl.force'));

instead of that one:

$this->_checks['ssl'] = ($this->request->is('ssl') && configure::read('app.ssl.force'));

(app become App).

**Comment by stripthis** [comment]
Hi @p4tpr0 yes we found out too. @kevinmuller did a fix for this on our development branch but we haven't release it yet on master. We are a bit caught up with all the exiting Chrome work :)

**Comment by stripthis** [comment]
Hello @p4tpr0, this issue was fixed with release v1.3.0.
Please feel free to reopen the issue if you run into this one again.
