### ISSUE TITLE
Can't create user with same email after deleting it.

### ISSUE THREAD

**Issue by gfriloux** [passbolt/passbolt_api#32]
Create a user, then delete it.
Recreate this user, with the same email address.
An error will be thrown :
```
error SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '402b74d8-f0ec-33dd-a6a0-e8bd66058def' for key 'PRIMARY'
```

From logs : 
```
2017-01-09 17:24:47 Error: [BadRequestException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '402b74d8-f0ec-33dd-a6a0-e8bd66058def' for key 'PRIMARY'
Request URL: /users
Stack Trace:
#0 /usr/share/webapps/passbolt/app/Controller/UsersController.php(224): MessageComponent->error('SQLSTATE[23000]...')
#1 [internal function]: UsersController->add()
#2 /usr/share/webapps/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 /usr/share/webapps/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /usr/share/webapps/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#5 /usr/share/webapps/passbolt/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
```

**Comment by gfriloux** [comment]
Deleting the entry in the users table fixes the issue.

**Comment by gfriloux** [comment]
Seems its not a good workaround, when listing users, i now see its account twice, while there is only one entry in the users table :)

**Comment by kevinmuller** [comment]
Hi Guillaume,

Actually, this "Integrity constraint violation" when you try to create another user with the same username (when the first one is deleted) happens only when you have the debug mode activated. 

This is due to the fact that in debug mode our uuids are generated in a predictable manner. So, for 2 same usernames it will generate the 2 same uuids, hence giving this error.

Set debug to 0 in your core.php file, and it will not give the error anymore.

Let me know it that fixes the issue.

Kevin

**Comment by gfriloux** [comment]
You are perfectly right! when debug mode is off, it works perfectly!
any idea of how to have the user to show only once, now (when listing users) ? :)

**Comment by kevinmuller** [comment]
It's probably due to a duplicate entry in the profiles table, for the same id. But maybe in some other tables too.
I'd say, if you can, do a full reinstall. It's generally not a good idea to modify data manually in the database and may lead to future side effects.
If you can't reinstall, in your database try to remove the duplicated entry that is in the "profiles" table for the same user_id. The relation between users and profiles should basically be 1:1, so there shouldn't be 2 entries for the same user in the profiles table.
Let me know.

**Comment by gfriloux** [comment]
Ok, there was indeed an old entry in the profiles table, probleme solved

**Comment by kevinmuller** [comment]
Great! :) 
Closing this thread.
