### ISSUE TITLE
A double new record is shown in the passsword grid when creating a new record

### ISSUE THREAD

**Issue by MG-Group-Italia** [passbolt/passbolt_api#328]
## Double new record
* Passbolt Version: 2.11.0
* Platform and Target:
-- Operating system: CentOS Linux 7
-- PHP: 7.2.21
-- Web server: nginx 1.12.2
-- Database server: mariadb 5.5.60

### What you did
Create new password record

### What happened
The record is double

**Comment by stripthis** [comment]
Hello @MG-Group-Italia ,

Can you try to logout, restart your browser and login again? Do you see the record in double still? Do you see a double record if you try to create a new one? If so can you check the browser console to see if there is any error.

We are not able to reproduce the issue, and we would need to have a step by step protocol to reproduce the issue in order to fix it. If you can spend some time to investigate and define such protocol it will be very helpful.

Thank you for the bug report

**Comment by MG-Group-Italia** [comment]
After reboot the server the problem look fixed. 
I'll keep test it in the next days
