### ISSUE TITLE
Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'email' doesn't have a default value 

### ISSUE THREAD

**Issue by buzzy3** [passbolt/passbolt_api#341]
Latest Pro Version, Mail is Working, Config set, MySQL Setup from Installer. Debian Buster 10

**Comment by stripthis** [comment]
Hello @buzzy3,

Can you please try to run:
- `./bin/cake cache clear_all`

If this doesn't solve it can you please try:
- clear your composer cache
- `composer clear-cache`
- clear cakephp cache
- `./bin/cake cache clear_all`
- delete the content of /vendor
- `rm -rf vendor`
- run composer install again
- `composer install`

Since you are using passbolt pro, the best would be to contact us at support@passbolt.com for any technical issue.
Best,
