### ISSUE TITLE
HTTP ERROR 500 "my.domain.com" is currently unable to handle this request.

### ISSUE THREAD

**Issue by feitan-root** [passbolt/passbolt_api#403]
Good day!

I just want to ask a help. I already did follow the instructions of installation:
https://help.passbolt.com/hosting/install/ce/ubuntu-18-04-bionic-beaver

i already did point host to webserver.

After the installation done i got the error. HTTP ERROR 500... on try to access on browser

i try to check logs on nignx and i got this error. 
2021/06/11 02:25:13 [error] 1409#1409: *13 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Your PHP version must be equal or higher than 7.3.0 to use Passbolt.in /var/www/passbolt/config/requirements.php on line 19" while reading response header from upstream, client: 192.168.*.*, server: mydomain.com, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mydomain.com"

Highly appreciate for your help.

**Comment by stripthis** [comment]
Hi, 

As mentionned on the issue template this space is reserved for bugs, if you have an installation issue, you can open a post on the community forum: https://community.passbolt.com, or if you are a passbolt pro customer you can contact us at support@passbolt.com. 

That being said, reading from the logs you gave, it seems your server does not meet the minimum requirements (eg. PHP < 7.3).

**Comment by linehammer** [comment]
The error is too generic and does not tell you exact problem. What you need is to find out what is the real issue. If your site is serving a Internal Server Error, this can be caused by a number of things, such as:

- Server permission
- Server timeout
- Script timeout
- Errors in .htaccess files
- Exceeded PHP memory limit.
- Or some other Web Server Issues

Normally, a permissions issue on the file (or files) would be one cause of the [500 Internal Server Error](http://net-informations.com/q/mis/500.html). The simple solution is to run chmod 644 on the problem file(s) or chmod 755 on the directories.

`$ sudo chmod -R 777 /"your files location"`

The best way to debug the error depends upon the server and what’s actually running at the time. Consider some debugging tips to help diagnose and fix common causes of this problem.

**Comment by stripthis** [comment]
> Consider some debugging tips to help diagnose and fix common causes of this problem.

```
sudo su -s /bin/bash -c "/usr/share/php/passbolt/bin/cake passbolt healthcheck" www-data
```
