### ISSUE TITLE
Error message on login with firefox 82

### ISSUE THREAD

**Issue by peckpeck** [passbolt/passbolt_api#404]
## Error message on login with firefox 82
* Passbolt Version: passbolt-pro-server  3.2.1-1
* Platform and Target:
-- Operating system: debian buster
-- PHP: 7.3.27
-- Web server: nginx 1.14.2
-- Database server: mariadb 10.3.27
-- Browser firefox 82.0.2, works with chromium

### What you did
My account was created.
I activated it, received an account activation notification email.
Then I try to login on passbolt with my firefox 82.0 browser.

### What happened

After typing the passphrase I get the following error :

x-gpgauth-authenticated should be set to false during stage1

Then i can click on the retry button and I come back to the login page.
This step works properly when using chromium.

### What you expected to happen

Have an access to passbolt.

**Comment by stripthis** [comment]
Hi,

Thanks for the report.
Do you have the same issue if you update to the current version of Firefox (89.0.1)?

**Comment by peckpeck** [comment]
Just installed firefox version 89 temporarily and it works

**Comment by BaaptM** [comment]
Hi,

I encounter the same error "x-gpgauth-authenticated should be set to false during stage1" with Firefox 89.0.2 but only when I try to login from a private browsing window.

I'm using passbolt pro version 3.2.2 docker container (5582b00eb156)

Do you have an update on this issue?

Thank you.

**Comment by garrettboone** [comment]
@BaaptM In the extension settings what do you have for `Run in Private Windows`?

![image](https://user-images.githubusercontent.com/47018474/129404642-4b81465c-7dc5-497c-829e-19b8422885f0.png)

**Comment by peckpeck** [comment]
I have "Don't allow"

**Comment by garrettboone** [comment]
@peckpeck In a private FF window (v92beta) the extension does not show for me in the tool tray and the login page of my passbolt site communicates the extension is not installed. Do you have any problems if in a normal window?

**Comment by peckpeck** [comment]
since the extension is not allowed for private windows this doesn't seem surprising.
My problem is for normal windows.

**Comment by garrettboone** [comment]
As FF has now released version 91, an update is recommended.

**Comment by peckpeck** [comment]
As the new debian stable contains firefox 82( which is not even 1 year old), it is not unreasonable to stay with it

**Comment by garrettboone** [comment]
Bullseye [runs ESR FF78](https://packages.debian.org/bullseye/firefox-esr) it seems.

**Comment by garrettboone** [comment]
@stripthis Do we have targeted browser versions for client side support?

**Comment by peckpeck** [comment]
Oh you're right ! 
This means my installation is not correct.
It may not a be a firefox version problem after all.

**Comment by stripthis** [comment]
We try to support the rapid release channel and latest ESR (both on 91 at the moment)

**Comment by zpeschke** [comment]
I know this is closed, but since this issue is in the top of search engine results when searching "firefox passbolt x-gpgauth-authenticated", I figured I'd add some info to my similar issue.

I'm running into this in Firefox 126.0, but it is due to my use of [Firefox containers](https://support.mozilla.org/en-US/kb/how-use-firefox-containers).

My guess is that the passbolt extension is authenticated outside of all containers. From my experience, LastPass works in a similar way. I get this error message when trying to open a link to my passbolt server: `x-gpgauth-authenticated should be set to false during the verify stage`.

A workaround is to open a new window that is not within a Firefox container and open your passbolt server URL there.
