### ISSUE TITLE
UI Improvement: Import Passwords error modal is very small

### ISSUE THREAD

**Issue by LordSimal** [passbolt/passbolt_api#476]
## Import Passwords error modal is very small
Passbolt Version: v3.11.1 (https://github.com/passbolt/passbolt_api/commit/b80a6606512370687dbb37065a6e1fba27d22413)
Platform and Target:
-- Operating system: Debian 11 Bullseye
-- PHP: 8.1.16 via FPM
-- Web server: NGINX 1.18.0
-- Database server: MariaDB 10.11.2

### What you did
With a fresh installation of passbolt I imported a CSV export of my previous password manager.

### What happened
After all passwords have been processed I have been greeted with the following message/warning:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/9105243/225422831-6726b58f-7b92-4b35-bb35-93f0fe926285.png">

### What you expected to happen
The error message is all fine and well but the fact, that the modal takes up like 20% of the browsers width + what you can see there is the maximum height I was able to adjust the textarea to so it was pretty bad to actually read the json error message in there.

I would appreciate a bigger error modal and/or the ability to change the modals size.

I attached the (adjusted) CSV file I imported to make it as reproducible as possbile (yes, I adjusted the password and removed all other data)
[PasswordExport.csv](https://github.com/passbolt/passbolt_api/files/10983966/PasswordExport.csv)

**Comment by Benj1er** [comment]
Hello @LordSimal,

Thank you for reporting this problem. A ticket has been create under the reference PB-24585.

After a first reading of the CSV file, the Url field of this password is not validated because it exceeds the expected character limit of 1024 and the url of your password is 1076 characters long.

We take into account your remarks and will try to display the json error much more readable to the user.

Best regards
