### ISSUE TITLE
KeePassx file export / import

### ISSUE THREAD

**Issue by Mte90** [passbolt/passbolt_api#48]
Will be very helpful a kdbx exporter of the password like a backup :-)

**Comment by stripthis** [comment]
File import and export is also on our roadmap and keepass integration definitely on our radar. Our vision is that we want to play nice with other open source password managers and work with them rather than replace them. @kevinmuller started doing some research for this feature here: https://docs.google.com/document/d/1iHokXa_aB9P9of0GXKKLnQIkBlY65iCDMX5IgvP7tss/edit?usp=sharing

**Comment by mindsolve** [comment]
Additionally to the libraries  listed by @kevinmuller there is an additional library for KeePass V2 files: https://github.com/keeweb/kdbxweb

**Comment by kevinmuller** [comment]
@mindsolve thanks for the suggestion. kdxweb looks quite promising indeed. I have added it to the document.

**Comment by mannp** [comment]
The trouble with allowing many and all clients to access the passbolt data is that you cannot control their security or integrity.

> play nice with other open source password managers and work with them rather than replace them

The reason I don't like the KeePassx's is that I have to use another android client say from another dev, which doesn't fill me with confidence that they are fully in sync and integrity is maintained.

I currently use 1Password and love it, but wish it was open source, which is why I am now trying Passbolt as a future replacement for it.

I hope you continue with Passbolt for me as a replacement for the others as a safer and better way to utilise passwords.

**Comment by passboltUser** [comment]
I'm sitting here, logging into our local server using KeePassXC to get the password, while noting that I the password I was searching for is located on our remote internet Passbolt server. Now, if internet or the remote server went down, that wouldn't be good. I need the passwords locally too (one never knows when the remote server for whatever reason isn't accessible), so an export feature to KeePassXC (for local password access) would be really handy/nice.

**Comment by mannp** [comment]
I'd prefer an android passbolt app with local password access :)

**Comment by stripthis** [comment]
Discussion moved to: https://community.passbolt.com/t/keepasx-file-export-and-import/16
