### ISSUE TITLE
Debian package has webroot/.htaccess missing

### ISSUE THREAD

**Issue by miklcct** [passbolt/passbolt_api#509]
##IMPORTANT: PLEASE READ

Only use github issues for bugs.

If you are certain this is a new API bug please use the following format:

## ISSUE NAME
* Passbolt Version: 4.6.0-1
* Platform and Target:
-- Operating system: Debian 12
-- PHP: 8.2
-- Web server: Apache 2.4
-- Database server: MariaDB 10.11.6
-- etc.: OTHER RELEVANT PLATFORM INFO

### What you did
I installed Passbolt and configured Apache to serve the webroot

### What happened
Apache returned HTTP 500 due to rewrite loop

After I downloaded webroot/.htaccess from Github and placed it into the server, it worked

### What you expected to happen
It loads correctly

**Comment by ishanvyas22** [comment]
👋🏼 Hey @miklcct, how did you installed & configured passbolt in your server? Did you followed our [installation guide](https://help.passbolt.com/hosting/install)? Or were you referring to any blog article online?

**Comment by miklcct** [comment]
I followed the installation guide except I didn't let it configure my web server because it would configure an Nginx instance.

I had an existing website with SSL already working using Apache on the port 443, so I had to configure a separate website for Passbolt on another port, using the existing SSL infrastructure.

**Comment by ishanvyas22** [comment]
Using package installer we recommend using vanilla server (you might have also seen note in the documentation) so it is expected that if you have some custom configuration then package might not work as expected. 

But since we provide option to configure web server or not so in this case it should behave properly. For now, I’m closing this issue but we’ll discuss internally if we can fix this.

Thank you for your report.
