### ISSUE TITLE
SMTP SETTINGS ERROR

### ISSUE THREAD

**Issue by Rizwana-ky** [passbolt/passbolt_api#510]
## ISSUE NAME
* Passbolt Version:  Latest version
* Platform and Target: vm
-- Operating system: ubuntu
-- SMTP server: Office365
-- Database server: mysql
-- etc.: OTHER RELEVANT PLATFORM INFO

### What you did
I tried to install passbolt thru this https://help.passbolt.com/hosting/install/ce/ubuntu/ubuntu.html link and when setting up the smtp settings i cannot send any test email even all the details i provided were correct

### What happened
now what its showing is This email is not associated with any approved users on this domain. Please contact your administrator to request an invitation link. even tho i used my own email id as adding a user

### What you expected to happen
i expected to successful installation but now i dont know how to recover this

**Comment by qntoni** [comment]
Hello @Rizwana-ky,

It looks like this is not something related to the Passbolt API itself, therefore I will close this ticket on GitHub. 

However, could you create a [community](https://community.passbolt.com) post regarding this issue? 

What I would need to know is:
- You said that the smtpSettings didn't send any test emails, did you navigate anyway to the next steps to finish the installation?
     - Have you took a look at our dedicated [email authentication guide](https://passbolt.com/docs/admin/emails/email-server/office365/) for Office365?
- Have you created the account after the installation? (as explained in [step 2.6](https://help.passbolt.com/hosting/install/ce/ubuntu/ubuntu.html)) 
    - Have you ever be able to log in after the installation?
- Since the email seems to not have been associated could you share the output from this MySQL query: `SELECT * FROM users;` ?

Thanks in advance.

Best regards
