### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by gianlucastella1** [passbolt/passbolt_api#53]
First of all, congrats for the great work you folks did at passbolt.

In order to implement passbolt in our company, I need to translate it in Italian.
I started generating a the default pot catalog created with
`app/Console/cake i18n extract`
and then I realized that most UI strings are hardcoded in JS.

1) is my statement correct or I missing something?
2) if yes, did you evaluate any JS i18n/gettext library out there? Any adoption plan?

Since I love passbolt, I would like contributing coding/translations.

Waiting your replies and comment

**Comment by stripthis** [comment]
Hi @gianlucastella1,

Yes we have strings a little bit everywhere, some are on [passbolt_api](http://github.com/passbolt/passbolt_api/) side (such as the error messages for the API responses and JS app). We used __() everywhere (except for the numerous places where we mistakely didn't) since we indeed had some plans for internationalization at the begining. 

**1. PHP side**
This one is the easiest, since it's native to cakephp. You can use the i18n console command as you stated.

**2. JS side**
On the JS side of the API code (e.g. the js code not in the extension) it works using the same dictionnary than cakephp. Indeed in our library the JS __() use a dictionnary file loaded from the DictionnaryController endpoint. So the baseline is already there, we need some process however to add these strings to the same .po file generated on step 1.

** 3. Plugin side***
Our plan is the ship the translations with the plugin (as it's the easiest, otherwise you need to have a more complex dictionaries versionning, as server and plugin version are not necessarily matching all the time).
We also have __() placeholders here but we hit a roadblock with the limitations of Firefox, that was not supporting internationalization in the content code (it was supporting it only in the addon code). This have changed with webextension, but we're not using webextension with Firefox yet. Long story short, it was not exactly a quicky one to make it cross browser compatible on the extension side, so we posponed it. 

If you are interested in helping there are a few things you can do to help. First let me know if that makes sense or if you have additional questions on where we are, we can take it together from there, and maybe organize a quick 101 chat if that can help us get started. I think an ideal first step should be to write down documentation about the overall architecture and how to reproduce the processes of extracting and translating strings, agree on changes we want to make to the existing setup and define a way forward.

Thank you for your interest in passbolt and talk to you soon.

**Comment by stripthis** [comment]
https://community.passbolt.com/t/as-a-user-i-should-be-able-to-use-passbolt-in-another-language-than-english/68
