### ISSUE TITLE
mysql user password with character '$' is not accepted (error: 1045)

### ISSUE THREAD

**Issue by alejojo** [passbolt/passbolt_api#57]
I tried with mariadb 5.5 and mysql-community 5.7 with same result.

This is the error:

```
mysqldump: Got error: 1045: Access denied for user 'pbuser'@'localhost' (using password: YES) when trying to connect
 Error: Something went wrong!
---------------------------------------------------------------

 Passbolt installation success! Enjoy! ☮
```

Then I changed the `$` character for another one and mysqldump created the file correctly.
I have found the solution here: http://stackoverflow.com/a/30098491/2025004

**Comment by kevinmuller** [comment]
Hi @alejojo 
Could this be due to the fact that you used the character $ between double quotes (like "pas$word") ? If it's the case, as for the example in brackets, then whatever string comes after $ will be interpreted as a variable and would cause the bug that you are describing.
Let me know if it was the case.

**Comment by alejojo** [comment]
Hi @kevinmuller,

yes, that was the case.
Cheers,
