### ISSUE TITLE
As a logged in user I should be able to share a password with a Group

### ISSUE THREAD

**Issue by shochdoerfer** [passbolt/passbolt_api#6]
I would love to see user groups implemented so that I am able to share an item with a whole group instead of sharing an item which each group member on a manual basis. Users should be able to belong to multiple groups.

**Comment by stripthis** [comment]
Hi stephan, yes groups are on our roadmap. If you look closely at the API you can see the endpoints are already there and that the permission system supports it. We need to build the UI for it though now!

https://github.com/passbolt/passbolt/blob/master/app/Controller/GroupsController.php
https://github.com/passbolt/passbolt/blob/master/app/Controller/GroupsUsersController.php

I will leave this ticket open so that you're informed when we rollout the feature.
Thanks for trying out passbolt,

**Comment by shochdoerfer** [comment]
Any idea when this feature will be ready? Is there a public roadmap somewhere to get any idea what other features you have planned and when they might be ready?

**Comment by stripthis** [comment]
We don't have an ETA right now for features, we will publish a feature/roadmap page on our website next week!

**Comment by stripthis** [comment]
See. https://medium.com/passbolt/how-passbolt-will-implement-groups-ee49108a6ff1#.yd1y6n2k9
ETA End of March

**Comment by cedricalfonsi** [comment]
Fixed with v1.5.1
