### ISSUE TITLE
Decryption failed during login server authentication

### ISSUE THREAD

**Issue by TurbaVladimir** [passbolt/passbolt_api#60]
I have installed passbolt, plugin in browser, done admin registration and now can't log in.
![image](https://cloud.githubusercontent.com/assets/6495967/24587094/9be050ac-17b8-11e7-8404-53107ca44739.png)
healthcheck shows that everything ok
![image](https://cloud.githubusercontent.com/assets/6495967/24587100/bc6d36f0-17b8-11e7-94f1-0e1354c27117.png)

Once i saw crashed chrome plugin.
Server logs in /app/tmp/logs/error.log do not show anything.

What should i do to make it work?

**Comment by stripthis** [comment]
Hello,

We have not seen this issue before even though we handle for this error case in the code.  This happens because the server is enabled to decrypt the challenge sent by your browser. It can be that the server key that is stored in the browser with this user is not the right one (like if you changed the server key after the user was registered). 

Can you try to do a recovery (go to https://<yourdomain>/recover ) for that user. If this doesn't solve it please send more information about your environment (which OS, which versions of all the stack elements) and your server key (the public key for example) so that we can try to reproduce the issue.

Concerning the chrome plugin crash that is also very unusual, but we've seen this incident (a memory corruption bug specific to a regression in chrome version 56, that affect but is not due to passbolt). Make sure you are using Chrome version 57. See. https://www.passbolt.com/incidents/20170210_chrome_not_available

**Comment by TurbaVladimir** [comment]
Yesterday i tried to debug extension and saw that it used method verify in authcontroller but received x-gpg-error* headers in response.
Then i tried to decrypt key, sent by extension using cli gpg and it asked for password of key.
Here i realise that i have to provide passphrase for passbolt, but in Config/app.php we see
` // PHP Gnupg module currently does not support passphrase, please leave blank`

Generated new gpg keys without passphrase and voila. It worked.

So here comes next question. How bad for security is using gpg keys without passphrase and is there any way to make them work any soon?
Also it would be handy to mention this crutch in  installation guides if it is the way it should work now.

And word about extension crashes. Idk how to debug them, but at least i can say that is use Chromium Version 57.0.2987.110 (64-bit) and they happend mostly when i spammed retry button.

**Comment by stripthis** [comment]
Thank you @TurbaVladimir for investigating this further.

**How bad for security is using gpg keys without passphrase?**

The server key is only used for authenticating the server (e.g to prove the identity of the server to the client) which is an optional component of the GPGAuth protocol. You can picture this as another safegard on top of the SSL certificate. Most classic HTTP authentication methods don't do that.

If the private key is leaked (to our knowledge there is no exploit to do that atm) it could be used to trick people into a fake passbolt instance. However the attacker would also need to be able to issue fake SSL certificate since each client is bound to an instance with both with a domain and a server key. Similarly if the private key is leaked because the attacker has access to the file system (as the webserver user), most likely encrypting the private key with a passphrase wouldn't help much since it will also be stored alongside on the server and accessible for that user. In both cases you would have bigger problems on your hands (since an attacker having file system access and/or a fake SSL cert is pretty much game over).

Considering encrypting the key only mitigate an unlikely scenario (where a SSL certificate is compromised and the private key is leaked an attacker having without access to file system), the risk of having no passphrase on the private server key is acceptable from my perspective.

**Is there any way to make them work any soon?**
This doesn't depend on us but the maintainers of library we use (http://php.net/manual/en/book.gnupg.php). As soon as it will be available there, our user will be able to use it (the config items are already in place). If we get larger adoption and this project substancial financial traction this is the type of 3rd party projects we could be funding.

**And word about extension crashes. Idk how to debug them, but at least i can say that i use Chromium Version 57.0.2987.110 (64-bit) and they happend mostly when i spammed retry button.**

Thanks we have created a follow up task in our backlog to investigate this issue. (ref. PASSBOLT-1990). I also created created a follow up to display better error messages when server key uses a passphrase (PASSBOLT-1991).
