### ISSUE TITLE
As a user, I want the ability to add entries which have TOTP keys such as GitHub / Amazon (2FA/MFA)

### ISSUE THREAD

**Issue by trobotham** [passbolt/passbolt_api#71]
I do apologize if this issue already exists however, I could not find it.

I am looking for a way to add TOTP tokens to entries/sites that support it (GitHub, Amazon, etc).

----

Admin Edit: see also, merged from #71

I have an idea to share which should be great if it's included in Passbolt.

## Example 

In fact I'm currently facing to a problem which cannot be solved by Passbolt yet.
I'm trying to share the AWS root account of my company. 
The strong password is already in my own Passbolt instance but isn't enough.
My Root account is secure by a MFA process, and I cannot share it securely.

## Idea 

So my idea is to share 2FA generator like we can already do with password. 
TOTP should be enough for a first shot but HOTP can be great also.
I thinks, It's possible to do that with the current GPG process. (For storing the "secret")
In UI, attached to an existing password entry  seems to be a good place.

## Resources

* [TOTP RFC](https://tools.ietf.org/html/rfc6238)
* [HOTP RFC](https://tools.ietf.org/html/rfc4226)

**Comment by stripthis** [comment]
Hello @trobotham, this is actually a new feature so no need to apologize :)

If you have time it would be very nice if you could you describe a little bit more the scenarios of how you would like this feature to work, so that it is easier to picture the feature for everyone involved?

Example for Github:
As a user I want to store TOTP initialization code in Passbolt
1. Loginto github, goes to settings, security under two-fractors authentication.
2. Clicks on "Set up two-factor authentication", click on "Set up using an app", click on "enter this text code"
3. Log into passbolt, on the password workspace, click on "new", select "TOTP token"
4. Copy the Github text code into passbolt create TOTP dialog
5. Save

As a user I want to use passbolt to generate a one time token to login into Github
1. Login passbolt, right click on the github TOTP entry, click on "copy OTP to clipboard"
2. Login into github, past the OTP token in the second authentication step input form, press login

Cheers,

**Comment by PierfrancescoElia** [comment]
Hi, this would be a very intresting feature.
As my passwords are on Passbolt, it would be intresting an integration with TOTP or HOTP.

This could be one of possible methods.
When I create a new Passbolt entry, I can tick a checkbox that would expanse the form with a filed for the secret, or something like that. Everything inside the dialog. No passwords linked with OTP entries..

I think that the possibility of using OTP when logging into Passbolt would be a great security enhacement.

**Comment by stripthis** [comment]
Moved to : https://community.passbolt.com/t/as-a-user-i-want-the-ability-to-add-entries-which-have-totp-keys-such-as-github-amazon-2fa-mfa/71
