### ISSUE TITLE
As an admin would like to be able to add a group as a member of another group

### ISSUE THREAD

**Issue by bluenetinc** [passbolt/passbolt_api#90]
The ability to created nested groups would make complex memberships easier to maintain.  I could assign fewer groups to passwords, and assign users to subgroups, with hierarchy to manage access to various password groups/categories

**Comment by stripthis** [comment]
We considered nested groups initially but it creates quite a bit of complexity to manage permissions. Example group A1 is a subgroup of A0, if Password P1 is shared as write with A1 and and read with A0, what is the permission of somebody in A1? From our user study some people will say it's read (most precise permission apply) some will say it write (highest permission apply). It gets even more confusing with nested groups inside nested categories.

We need help to define all these scenarios so that we can review it with the community in order to make something that make sense for most people. I'm curious about hearing about your specific use case @bluenetinc, like how many groups do you have, what kind of hierachy and permission you need. Maybe there are other ways to design a solution for this problem.

**Comment by bluenetinc** [comment]
Yes, that is a can of worms I've opened... I'm wondering if categories/tags would mitigate the need for nested groups.. (ie: are you planning to allow someone to assign all passwords in a folder/category/tag to a user/group?)  If you did that, I would have less need for nesting groups to make assigning several passwords to several users/groups easier...   

I think I need to whiteboard this a bit more and give you more detailed feedback.  Is there a discussion area on how the tags/categories implementation would likely be implemented, or is it to early in design to answer that today?

**Comment by stripthis** [comment]
Indeed nested groups and categories are the same class of issues and related to the same problem. There is ticket for categories but it's empty: https://github.com/passbolt/passbolt_api/issues/30

Most discussions I had with @kevinmuller and @cedricalfonsi were not paper but we will start writting things down at some point. We don't have the same opinions about it and our ideas have evolved since we first talked about it / implemented some prototype endpoints for categories in the v.1.1 API (which we removed since).

There are important design decisions like for example on the categories. For example is it like groups, e.g. do you have a shared tree structure for everybody? Who can set these categories then? If everybody has their own categories tree how do we maintain consitent and easily understandable permissions since nobody has the same view? Do we have both one personal category tree and an organization-wide one?

For now I'm personally leaning having a personal only category tree. When you share a category with a group or somebody you assign permissions to the entries inside it, overriding the properties (if you are allowed to), e.g. categories permission are a way to "script" a permission change that affect a lot of entries but you don't keep that view (you can only affect new permissions not see the current ones). But I know @kevinmuller is not a big fan of this.

If you want to think about this issue @bluenetinc and maybe write a blog or a document about it that would be very usefull and encourage other people to do the same. This way we can start the discussion with some common understanding of the issues.

**Comment by stripthis** [comment]
@bluenetinc I found a document in our archive that might interest you https://docs.google.com/document/d/19Z-7AzdJjWaODidhIwE4fB6zarYa6o3xeqE5fTqloZc/edit?usp=sharing

**Comment by bluenetinc** [comment]
After further thought I am thinking nested groups would be better managed via LDAP integration.  Also, I think I would prefer to grant permissions to a group at a folder hierarchy rather than trying to manage the added security complexity within Passbolt itself that you mentioned previously.  That being said, if nested groups is not available in Passbolt natively, I would need to inherit this via LDAP, AND/OR be able to grant permissions at a group/folder/category level to make management of larger teams easier.
